language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

install:
  - pip install coverage coveralls --use-mirrors

script: coverage run setup.py test

after_success: coveralls